### ISSUE TITLE
3D AN?

### ISSUE THREAD

**Issue by OverLordGoldDragon** [Cyril9227/Keras_AttentiveNormalization#2]
It appears this implementation only supports 4D inputs - though `Conv1D` takes and outputs 3D tensors; I found that making below changes enables AN to work for 3D tensors without errors:

```
GlobalAveragePooling2D() --> GlobalAveragePooling1D()
gamma_readjust[:, None, None, :] --> gamma_readjust[:, None, :]
beta_readjust[:, None, None, :] --> beta_readjust[:, None, :] 
```
I'm unsure, however, whether this is a _correct_ implementation consistent with the paper - can you confirm? Thanks

**Comment by Cyril9227** [comment]
Thank's for your feedback.

Sure, you are right. Feel free to make a pull request for this

**Comment by OverLordGoldDragon** [comment]
Thank you for your implementation
