### ISSUE TITLE
Question about the weight of each channel

### ISSUE THREAD

**Issue by ZhangYuanhan-AI** [Cyril9227/Keras_AttentiveNormalization#4]
![image](https://user-images.githubusercontent.com/18485270/69024326-3ba0ef00-09fd-11ea-880f-c946a2c92f0a.png)
First, thanks for sharing this work.But I have some confusion, as what I show in this pic. Do you mean that for each batch(like N_0), for each channel in this batch.the weight(the dimension is K) is the same?Because I also notice that the shape of the output of the sigmoid is the (N*K).
Thanks for your answer.

**Comment by Cyril9227** [comment]
Hello, thank's for your interest. I want first to clarify that the paper is not my work, I only did a Keras port of the original work.

Yes, for each channel you will learn K parameters that will be used for the affine transformation.
