### ISSUE TITLE
Can not run test script

### ISSUE THREAD

**Issue by iamgmujtaba** [Cyril9227/Keras_AttentiveNormalization#5]
Hi There, 

I have tried to run the test script several times but not running.

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-9-aeab17cecff8> in <module>
      1 inp = Input((64, 64, 3))
      2 x = Dense(20, activation="relu")(inp)
----> 3 x = AttentiveNormalization(n_mixture=5, momentum=0.99, epsilon=0.001, axis=-1)(x)

TypeError: list indices must be integers or slices, not ListWrapper

My configurations:
python 3.6
TensorFlow-GPU 2.0.0
Keras 2.2.4

**Comment by Cyril9227** [comment]
You mean running the notebook as it yields this error ? Never saw it before, I'll take a look when I have the chance, a bit swamped by work right now

**Comment by iamgmujtaba** [comment]
Thank you for your response. Yes, the notebook. 
Maybe it is due to Keras or TensorFlow's version.
If possible, please share your configuration or requirement.txt file.
Okay, I will wait for your feedback.

**Comment by Cyril9227** [comment]
Aww shit, might be the latest Tensorflow version

Maybe you could try updating the code using tensorflow.keras instead of the Keras API which is currently not maintained

I'll take a look

**Comment by iamgmujtaba** [comment]
I have used  tensorflow.keras.something instead of keras.somthing.something on TensorFlow 2.0.0 versions
In addition, I have downgraded the TensorFlow version to 1.14.0, still the same error.

**Comment by iamgmujtaba** [comment]
I had another problem. 

AttentiveNormalization.py", line 61, in call
    if len(input_shape) == 4:
NameError: name 'input_shape' is not defined


I am testing my code like this.

layer5 = MaxPooling2D((2, 2), name="globalPoolLayer")(input_layer)
layer5 = AttentiveNormalization(n_mixture=5, momentum=0.99, epsilon=0.001, axis=-1)(layer5)

Please give your kind suggestions.
Thanks
